name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - bugfix-ci-*

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./bookit-front

      - name: Build
        run: npm run build
        env:
          VITE_BACKEND_BASE_URL: http://localhost:5713
        working-directory: ./bookit-front
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEBUG: "semantic-release:*"
      
      - name: Set Image Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_ENV
          fi

      - name: Check new release versions
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
          echo ${{ env.IMAGE_TAG }}
      
      - name: Kaniko Build and Push
        uses: aevea/action-kaniko@master
        with:
          image: gpavle/bookit-front
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          extra_args: "--reproducible --force"
          debug: true
          tag: ${{ env.IMAGE_TAG }}

